/**
 * AdvertisementDataSource provides CRUD operations for the `advertisement`
 * store within IndexedDB.  This module ports a subset of the methods
 * defined in the Android `AdvertisementDataSource` class.  Records
 * inserted into this store should use property names that mirror the
 * column names defined in `MySQLiteHelper` (e.g. `adv_id`,
 * `adv_name`, `adv_minute`, etc.).  See
 * `MySQLiteHelper` for the full list of columns (e.g.
 * `adv_minute`, `adv_song`, `adv_time`, `adv_play_type`,
 * `adv_sound_type`, `adv_serial_no`, `adv_total_min`,
 * `adv_total_song`, `adv_end_date`, `adv_start_date`,
 * `adv_start_time`, `adv_path`, `download_status`,
 * `timeinterval`, `flavour`, `playlistid`, `endtimechk`,
 * `start_time_in_millis_adv`, `end_time_in_millis_adv`,
 * `btStart_time_in_millis_adv`).
 *
 * Each method returns a promise and does not throw synchronously.
 */
(function () {
  class AdvertisementDataSource {
    /**
     * Insert a new advertisement record.  If the object does not
     * contain an `_id` property an auto‑incrementing key will be
     * generated by IndexedDB.  The returned promise resolves with
     * the inserted record including its assigned `_id`.
     *
     * @param {Object} ad Advertisement record with fields such as
     *   adv_file_url, adv_id, adv_name, adv_is_min, adv_is_song,
     *   adv_is_time, adv_ply_type, adv_sound_type, adv_serial_no,
     *   adv_total_min, adv_total_songs, adv_e_date, adv_s_date,
     *   adv_s_time, adv_path, set_download_status, TimeIntervalAds,
     *   adv_flavour, adv_play_id, adv_endTimeRef, start_time_in_millis_adv,
     *   end_time_in_millis_adv, btStart_time_in_millis_adv.
     */
    async createAdvertisement(ad) {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.advertisement.add(ad);
          req.onsuccess = () => {
            ad._id = req.result;
            resolve(Object.assign({}, ad));
          };
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Update an existing advertisement record.  The `ad` object
     * must include an `_id` property corresponding to the record to
     * update.  Returns a boolean indicating success.
     */
    async updateAdvertisement(ad) {
      if (!('_id' in ad)) {
        throw new Error('updateAdvertisement requires _id on the advertisement object');
      }
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.advertisement.put(ad);
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Check whether an advertisement with the same `adv_id` exists.
     * If it does the record is updated, otherwise a new record is
     * created.  Returns a boolean indicating whether an existing
     * record was updated (`true`) or a new record was created (`false`).
     */
    async checkifExistAdv(ad) {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const advId = ad.adv_id;
          // Iterate the entire store because no index exists yet.  If
          // performance becomes an issue an index on adv_id could be
          // added in DB.onupgradeneeded.
          const req = stores.advertisement.openCursor();
          let foundCursor = null;
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              if (cursor.value.adv_id === advId) {
                foundCursor = cursor;
                // update existing record
                const updated = Object.assign({}, cursor.value, ad, { _id: cursor.value._id });
                cursor.update(updated);
                cursor.continue();
                // continue scanning to finish transaction
              } else {
                cursor.continue();
              }
            } else {
              if (foundCursor) {
                resolve(true);
              } else {
                // not found; insert new
                const addReq = stores.advertisement.add(ad);
                addReq.onsuccess = () => resolve(false);
                addReq.onerror = () => reject(addReq.error);
              }
            }
          };
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Retrieve all advertisements where `set_download_status` equals 0
     * (i.e. not yet downloaded).  Returns an array of records.
     */
     async getAdvThoseAreNotDownloaded() {
      return DB.withTransaction(['advertisement'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const ad = cursor.value;
              if (Number(ad.download_status) === 0) {
                result.push(ad);
              }
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Update the download status and file path for a given
     * advertisement.  The advertisement object must include the
     * `_id` property (auto‑generated key) and the fields
     * `set_download_status` and `adv_path` to update.  Other fields
     * remain unchanged.
     */
    async updateDownloadStatusAndPath(ad) {
      const { _id, download_status, adv_path } = ad;
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const getReq = stores.advertisement.get(_id);
          getReq.onsuccess = (event) => {
            const existing = event.target.result;
            if (existing) {
              existing.download_status = download_status;
              existing.adv_path = adv_path;
              stores.advertisement.put(existing);
            }
            resolve(true);
          };
          getReq.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Retrieve all advertisements where `set_download_status` equals 1
     * (downloaded).  Records are sorted by `start_time_in_millis_adv`
     * ascending to mirror the original SQL query.  Returns an array.
     */
    async getAllAdv() {
      return DB.withTransaction(['advertisement'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const ad = cursor.value;
              if (Number(ad.download_status) === 1) {
                result.push(ad);
              }
              cursor.continue();
            } else {
              // sort by start time if available
              result.sort((a, b) => {
                return (a.start_time_in_millis_adv || 0) - (b.start_time_in_millis_adv || 0);
              });
              resolve(result);
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Delete an advertisement record.  If `deleteSourceFile` is true
     * this method would remove the associated media file in the
     * Android implementation.  In webOS we cannot delete arbitrary
     * files so the flag is ignored.  Records are removed by `_id`.
     */
    async deleteAds(ad, deleteSourceFile = false) {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.advertisement.delete(ad._id);
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Return advertisements whose `adv_id` is not present in the
     * provided array of IDs.  This is used to remove stale entries
     * after syncing with the server.
     *
     * @param {string[]} advIds Array of advertisement IDs received
     *   from the server.
     * @returns {Promise<Object[]>} List of obsolete advertisement records.
     */
    async getListNotAvailableinWebResponse(advIds) {
      return DB.withTransaction(['advertisement'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const ad = cursor.value;
              if (!advIds.includes(ad.adv_id)) {
                result.push(ad);
              }
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Update the `set_download_status` of a record to 0 (not downloaded)
     * by its `_id`.  This mirrors the behaviour of the Android
     * `updateAdvColumnDownloadStatus` method.
     */
    async updateAdvColumnDownloadStatus(id) {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const getReq = stores.advertisement.get(Number(id));
          getReq.onsuccess = (event) => {
            const existing = event.target.result;
            if (existing) {
              existing.download_status = 0;
              stores.advertisement.put(existing);
            }
            resolve(true);
          };
          getReq.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Retrieve advertisements of type `isTime` that should start
     * within ±2 seconds of the current time.  Only downloaded
     * advertisements (set_download_status == 1) are returned.  This
     * mirrors the behaviour of the Java `getIsTimeAdv` method but
     * simplified for webOS.
     */
    async getIsTimeAdv() {
      const now = Date.now();
      const low = now - 2000;
      const high = now + 2000;
      return DB.withTransaction(['advertisement'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const ad = cursor.value;
              const start = ad.start_time_in_millis_adv;
              if (Number(ad.download_status) === 1 && start != null) {
                if (start >= low && start <= high) {
                  result.push(ad);
                }
              }
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Delete all advertisements from the database.
     * Mirrors Java `deleteAdvIfNotInServer` which clears the entire table.
     */
    async deleteAdvIfNotInServer() {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const clearReq = stores.advertisement.clear();
          clearReq.onsuccess = () => {
            console.log('[ADV_DS] deleteAdvIfNotInServer SUCCESS');
            resolve(true);
          };
          clearReq.onerror = () => {
            console.error('[ADV_DS] deleteAdvIfNotInServer FAIL');
            resolve(false);
          };
        });
      });
    }

    /**
     * Delete all unused advertisements from the database.
     * Mirrors Java `deleteAdvUnUsed` which clears the entire table.
     */
    async deleteAdvUnUsed() {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const clearReq = stores.advertisement.clear();
          clearReq.onsuccess = () => {
            console.log('[ADV_DS] deleteAdvUnUsed SUCCESS');
            resolve(true);
          };
          clearReq.onerror = () => {
            console.error('[ADV_DS] deleteAdvUnUsed FAIL');
            resolve(false);
          };
        });
      });
    }

    /**
     * Get advertisements that are marked as downloaded but their files
     * don't exist in storage. Since we can't check file existence in browser,
     * we check if adv_path is empty/null and update download_status.
     * Mirrors Java `getNotExistInStorage`.
     *
     * @returns {Promise<Object[]>} List of advertisements needing re-download.
     */
    async getNotExistInStorage() {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const ad = cursor.value;
              if (Number(ad.download_status) === 1) {
                // In browser environment, check if path is empty/null
                // In Java, this checks if file exists on filesystem
                if (!ad.adv_path) {
                  // Update status to not downloaded
                  ad.download_status = 0;
                  cursor.update(ad);
                  result.push(ad);
                }
              }
              cursor.continue();
            } else {
              console.log('[ADV_DS] getNotExistInStorage SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[ADV_DS] getNotExistInStorage FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Delete advertisements by their adv_id (not _id).
     * Matches Java behavior where deletion is by adv_id column.
     *
     * @param {string} advId The adv_id to delete.
     * @param {boolean} deleteSourceFile Whether to delete the source file (ignored in browser).
     */
    async deleteAdsByAdvId(advId, deleteSourceFile = false) {
      return DB.withTransaction(['advertisement'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const req = stores.advertisement.openCursor();
          let deleted = false;
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              if (cursor.value.adv_id === advId) {
                cursor.delete();
                deleted = true;
              }
              cursor.continue();
            } else {
              console.log('[ADV_DS] deleteAdsByAdvId SUCCESS advId=' + advId + ' deleted=' + deleted);
              resolve(deleted);
            }
          };
          req.onerror = () => {
            console.error('[ADV_DS] deleteAdsByAdvId FAIL advId=' + advId);
            resolve(false);
          };
        });
      });
    }

    /**
     * Get all advertisements (both downloaded and not downloaded).
     * Useful for cleanup operations.
     */
    async getAllAdvertisements() {
      return DB.withTransaction(['advertisement'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.advertisement.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              result.push(cursor.value);
              cursor.continue();
            } else {
              console.log('[ADV_DS] getAllAdvertisements SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[ADV_DS] getAllAdvertisements FAIL');
            resolve([]);
          };
        });
      });
    }
  }

  window.AdvertisementDataSource = AdvertisementDataSource;
})();