/**
 * PlaylistDataSource implements a subset of the methods defined in the
 * Android `PlaylistDataSource` class but backed by IndexedDB.  Each
 * method returns a promise resolving to the requested data.  Record
 * objects must conform to the column names defined in the original
 * SQLite schema (see `MySQLiteHelper`), including `_id` when
 * updating existing entries.
 */
(function () {
  class PlaylistDataSource {
    /**
     * Insert a new playlist record.  If the object does not contain an
     * `_id` property an auto‑incrementing key will be generated by
     * IndexedDB.  The returned promise resolves with the inserted
     * record including its assigned `_id`.
     *
     * @param {Object} playlist Playlist record with fields such as
     *   sch_id, sp_playlist_id, start_time, end_time, sp_name,
     *   startTimeInMilli, endTimeInMilli, isseprationactive,
     *   playlistcategory and playlistvol.
     */
    async createPlaylist(playlist) {
      return DB.withTransaction(['playlist'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.playlist.add(playlist);
          req.onsuccess = () => {
            playlist._id = req.result;
            resolve(Object.assign({}, playlist));
          };
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Update an existing playlist record.  The playlist object must include
     * the `_id` of the record to be updated.  Returns a boolean
     * indicating whether the update succeeded.
     */
    async updatePlayList(playlist) {
      if (!('_id' in playlist)) {
        throw new Error('updatePlayList requires _id on the playlist object');
      }
      return DB.withTransaction(['playlist'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.playlist.put(playlist);
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Remove a playlist record by its internal `_id`.
     */
    async deletePlaylistById(id) {
      return DB.withTransaction(['playlist'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.playlist.delete(id);
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Delete all playlists and reset the auto‑increment counter.
     */
    async deletePlaylist() {
      return DB.withTransaction(['playlist'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const clearReq = stores.playlist.clear();
          clearReq.onsuccess = () => resolve(true);
          clearReq.onerror = () => reject(clearReq.error);
        });
      });
    }

    /**
     * Retrieve playlists that are currently active.  A playlist is
     * considered active if the current time (in milliseconds) is
     * greater than or equal to its startTimeInMilli and strictly less
     * than its endTimeInMilli.  Returns an array of matching records.
     */
    async getAllPlaylists() {
      const nowAbsolute = Date.now();
      const nowReference = this._getCurrentTimeInMilli();
      const referenceCutoff = new Date(2000, 0, 1).getTime();
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              const start = Number(item.startTimeInMilli || 0);
              const end = Number(item.endTimeInMilli || 0);
              if (start && end) {
                const useReferenceClock = start < referenceCutoff && end < referenceCutoff;
                const now = useReferenceClock ? nowReference : nowAbsolute;
                const isActive = end >= start
                  ? (now >= start && now < end)
                  : (now >= start || now < end);
                if (isActive) {
                  result.push(item);
                }
              }
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => resolve(result);
        });
      });
    }

    /**
     * Retrieve playlists whose end time has not yet elapsed.  This
     * matches the behaviour of the Java `getPlaylistsForCurrentAndComingTime`
     * method which returns playlists scheduled for now and the future.
     */
    async getPlaylistsForCurrentAndComingTime() {
      const nowAbsolute = Date.now();
      const referenceCutoff = new Date(2000, 0, 1).getTime();
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              const start = Number(item.startTimeInMilli || 0);
              const end = Number(item.endTimeInMilli || 0);
              if (start && end) {
                const useReferenceClock = start < referenceCutoff && end < referenceCutoff;
                if (useReferenceClock) {
                  // Time-of-day schedules are valid every day; keep them for active-window checks.
                  result.push(item);
                } else if (end >= nowAbsolute) {
                  result.push(item);
                }
              }
              cursor.continue();
            } else {
              // sort by start time ascending to mirror SQL ordering
              result.sort((a, b) => (a.startTimeInMilli || 0) - (b.startTimeInMilli || 0));
              resolve(result);
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Retrieve one representative playlist for each distinct
     * `sp_playlist_id`.  The representative chosen is the first one
     * encountered during iteration.  This mirrors the behaviour of
     * the Java `getAllDistinctPlaylists` method which performs a
     * `SELECT DISTINCT sp_playlist_id` query.
     */
    async getAllDistinctPlaylists() {
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const resultMap = new Map();
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              if (!resultMap.has(item.sp_playlist_id)) {
                resultMap.set(item.sp_playlist_id, item);
              }
              cursor.continue();
            } else {
              resolve(Array.from(resultMap.values()));
            }
          };
          req.onerror = () => resolve([]);
        });
      });
    }

    /**
     * Check if a playlist with the same schedule ID exists.  If it
     * exists the record is updated, otherwise a new record is created.
     * Returns a boolean indicating whether an existing record was
     * updated (`true`) or a new record was created (`false`).
     */
    async checkifPlaylistExist(playlist) {
      return DB.withTransaction(['playlist'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const idx = stores.playlist.index('sch_id_idx');
          const single = idx.get(playlist.sch_id);
          single.onsuccess = () => {
            const existing = single.result;
            if (existing) {
              // preserve the _id on update
              const updated = Object.assign({}, existing, playlist, { _id: existing._id });
              const putReq = stores.playlist.put(updated);
              putReq.onsuccess = () => resolve(true);
              putReq.onerror = () => reject(putReq.error);
            } else {
              const addReq = stores.playlist.add(playlist);
              addReq.onsuccess = () => resolve(false);
              addReq.onerror = () => reject(addReq.error);
            }
          };
          single.onerror = () => reject(single.error);
        });
      });
    }

    /**
     * Retrieve all playlists ordered by start_time.  Mirrors Java
     * `getAllPlaylistsInPlayingOrder` which returns all playlists
     * sorted by COLUMN_START_TIME ascending.
     */
    async getAllPlaylistsInPlayingOrder() {
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              result.push(cursor.value);
              cursor.continue();
            } else {
              // Sort by startTimeInMilli ascending to match Java ORDER BY start_time
              result.sort((a, b) => (a.startTimeInMilli || 0) - (b.startTimeInMilli || 0));
              console.log('[PLAYLIST_DS] getAllPlaylistsInPlayingOrder SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PLAYLIST_DS] getAllPlaylistsInPlayingOrder FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Retrieve playlists that are scheduled to start in the future.
     * Mirrors Java `getRemainingAllPlaylists` which returns playlists
     * where startTimeInMilli >= currentTime AND endTimeInMilli >= currentTime.
     */
    async getRemainingAllPlaylists() {
      const now = this._getCurrentTimeInMilli();
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              if (item.startTimeInMilli >= now && item.endTimeInMilli >= now) {
                result.push(item);
              }
              cursor.continue();
            } else {
              result.sort((a, b) => (a.startTimeInMilli || 0) - (b.startTimeInMilli || 0));
              console.log('[PLAYLIST_DS] getRemainingAllPlaylists SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PLAYLIST_DS] getRemainingAllPlaylists FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Retrieve playlists that have already ended (past playlists).
     * Mirrors Java `getPendingPastPlaylist` which returns playlists
     * where startTimeInMilli < currentTime AND endTimeInMilli < currentTime.
     */
    async getPendingPastPlaylist() {
      const now = this._getCurrentTimeInMilli();
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              if (item.startTimeInMilli < now && item.endTimeInMilli < now) {
                result.push(item);
              }
              cursor.continue();
            } else {
              console.log('[PLAYLIST_DS] getPendingPastPlaylist SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PLAYLIST_DS] getPendingPastPlaylist FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Retrieve playlists whose sch_id is NOT in the provided array.
     * Used to find stale playlists after syncing with server.
     * Mirrors Java `getListNotAvailableinWebResponse`.
     *
     * @param {string[]} schIdArray Array of schedule IDs from server.
     * @returns {Promise<Object[]>} List of obsolete playlist records.
     */
    async getListNotAvailableinWebResponse(schIdArray) {
      if (!Array.isArray(schIdArray)) schIdArray = [];
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              if (!schIdArray.includes(item.sch_id)) {
                result.push(item);
              }
              cursor.continue();
            } else {
              console.log('[PLAYLIST_DS] getListNotAvailableinWebResponse SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PLAYLIST_DS] getListNotAvailableinWebResponse FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Retrieve playlists whose end time has already passed.
     * Mirrors Java `getPlaylistGoneTime` which returns playlists
     * where currentTime > endTimeInMilli.
     */
    async getPlaylistGoneTime() {
      const now = this._getCurrentTimeInMilli();
      return DB.withTransaction(['playlist'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.playlist.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const item = cursor.value;
              if (now > item.endTimeInMilli) {
                result.push(item);
              }
              cursor.continue();
            } else {
              console.log('[PLAYLIST_DS] getPlaylistGoneTime SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PLAYLIST_DS] getPlaylistGoneTime FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Helper to compute current time in milliseconds normalized to
     * the 1/1/1900 base date used by Java for time-of-day comparisons.
     * This mirrors the Java pattern of comparing times within a fixed
     * reference date to handle time windows that span midnight.
     */
    _getCurrentTimeInMilli() {
      const now = new Date();
      // Create a date with the reference date 1/1/1900 but current time
      const refDate = new Date(1900, 0, 1, now.getHours(), now.getMinutes(), now.getSeconds(), now.getMilliseconds());
      return refDate.getTime();
    }
  }

  // Expose globally
  window.PlaylistDataSource = PlaylistDataSource;
})();