/**
 * PlayerStatusDataSource provides CRUD operations for the
 * `table_player_status` store.  It mirrors a subset of the
 * functionality offered by the Android `PlayerStatusDataSource` class.
 *
 * Records inserted into this store should use property names that
 * match the SQLite column names (e.g. `login_date`, `login_time`,
 * `artist_id_song`, etc.).
 */
(function () {
  class PlayerStatusDataSource {
    /**
     * Insert a new player status entry.  If the object does not
     * contain an `_id` property an auto‑incrementing key will be
     * generated by IndexedDB.
     *
     * @param {Object} status Status record including fields such as
     *   login_date, login_time, logout_date, logout_time,
     *   artist_id_song, played_date_time_song, title_id_song,
     *   spl_playlist_id_song, heartbeat_datetime,
     *   advertisement_id_status, advertisement_played_date,
     *   advertisement_played_time, prayer_played_date,
     *   prayer_played_time, is_player_status_type.
     */
    async createPlayerStatus(status) {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.table_player_status.add(status);
          req.onsuccess = () => {
            status._id = req.result;
            resolve(Object.assign({}, status));
          };
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Retrieve the most recent five statuses of a given type.  The
     * `type` corresponds to the `is_player_status_type` field
     * (e.g. 'song', 'login', 'logout', 'ad', 'heartbeat', etc.).
     * Records are returned in descending order of insertion (newest
     * first).
     *
     * @param {string} type The status type to filter on.
     * @returns {Promise<Object[]>} Array of up to five status records.
     */
    async getPlayedSongs(type) {
      return DB.withTransaction(['table_player_status'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const index = stores.table_player_status.index('player_status_type_idx');
          const range = IDBKeyRange.only(type);
          // Iterate in reverse order by specifying direction 'prev'
          const req = index.openCursor(range, 'prev');
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor && result.length < 5) {
              result.push(cursor.value);
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => resolve(result);
        });
      });
    }

    /**
     * Alias for getPlayedSongs.  Included for parity with the
     * Android API which provides both `getPlayedSongs` and
     * `getPlayedSongsNew` methods with identical behaviour.
     */
    async getPlayedSongsNew(type) {
      return this.getPlayedSongs(type);
    }

    /**
     * Delete all player status entries of the given type.
     *
     * @param {string} type The status type to remove.
     */
    async deletePlayedStatus(type) {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const index = stores.table_player_status.index('player_status_type_idx');
          const range = IDBKeyRange.only(type);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              cursor.delete();
              cursor.continue();
            } else {
              resolve(true);
            }
          };
          req.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Delete status entries of the given type and specific `title_id_song`.
     */
    async deletePlayedSongStatus(type, titleIdSong) {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const req = stores.table_player_status.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const value = cursor.value;
              if (value.is_player_status_type === type && value.title_id_song === titleIdSong) {
                cursor.delete();
              }
              cursor.continue();
            } else {
              resolve(true);
            }
          };
          req.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Delete status entries of the given type, specific
     * `title_id_song` and exact `played_date_time_song` value.
     */
    async deletePlayedSongStatusForTime(type, titleIdSong, playedDateTime) {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const req = stores.table_player_status.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const value = cursor.value;
              if (value.is_player_status_type === type && value.title_id_song === titleIdSong && value.played_date_time_song === playedDateTime) {
                cursor.delete();
              }
              cursor.continue();
            } else {
              resolve(true);
            }
          };
          req.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Delete status entries of the given type and advertisement ID.
     */
    async deletePlayedAdvStatus(type, advId) {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const req = stores.table_player_status.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const value = cursor.value;
              if (value.is_player_status_type === type && value.advertisement_id_status === advId) {
                cursor.delete();
              }
              cursor.continue();
            } else {
              resolve(true);
            }
          };
          req.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Delete all entries in the `table_player_status` store.  This is
     * equivalent to dropping and recreating the table in SQLite.
     */
    async deletePlayerStatusTable() {
      return DB.withTransaction(['table_player_status'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.table_player_status.clear();
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }
  }

  window.PlayerStatusDataSource = PlayerStatusDataSource;
})();