/**
 * PrayerDataSource provides CRUD operations for the `prayer` store within
 * IndexedDB. This module ports the methods defined in the Android
 * `PrayerDataSource` class (if it exists) or provides equivalent
 * functionality based on the Prayers model. Records inserted into this
 * store should use property names that mirror the column names defined
 * in `MySQLiteHelper` for prayer data.
 *
 * Prayer record fields:
 * - _id: Auto-generated key
 * - response: Response string
 * - end_prayer_date: End date for prayer time
 * - end_prayer_time: End time for prayer
 * - start_prayer_date: Start date for prayer time
 * - start_prayer_time: Start time for prayer
 * - start_time_in_milli_prayer: Start time in milliseconds
 * - end_time_in_milli_prayer: End time in milliseconds
 *
 * Each method returns a promise and does not throw synchronously.
 */
(function () {
  class PrayerDataSource {
    /**
     * Insert a new prayer record. If the object does not contain an
     * `_id` property an auto-incrementing key will be generated by
     * IndexedDB. The returned promise resolves with the inserted
     * record including its assigned `_id`.
     *
     * @param {Object} prayer Prayer record with fields.
     */
    async createPrayer(prayer) {
      return DB.withTransaction(['prayer'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.prayer.add(prayer);
          req.onsuccess = () => {
            prayer._id = req.result;
            console.log('[PRAYER_DS] createPrayer SUCCESS id=' + prayer._id);
            resolve(Object.assign({}, prayer));
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] createPrayer FAIL', req.error);
            reject(req.error);
          };
        });
      });
    }

    /**
     * Update an existing prayer record. The prayer object must include
     * the `_id` property corresponding to the record to update.
     * Returns a boolean indicating success.
     */
    async updatePrayer(prayer) {
      if (!('_id' in prayer)) {
        throw new Error('updatePrayer requires _id on the prayer object');
      }
      return DB.withTransaction(['prayer'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.prayer.put(prayer);
          req.onsuccess = () => {
            console.log('[PRAYER_DS] updatePrayer SUCCESS id=' + prayer._id);
            resolve(true);
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] updatePrayer FAIL', req.error);
            reject(req.error);
          };
        });
      });
    }

    /**
     * Delete a prayer record by its internal `_id`.
     */
    async deletePrayer(id) {
      return DB.withTransaction(['prayer'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.prayer.delete(id);
          req.onsuccess = () => {
            console.log('[PRAYER_DS] deletePrayer SUCCESS id=' + id);
            resolve(true);
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] deletePrayer FAIL', req.error);
            reject(req.error);
          };
        });
      });
    }

    /**
     * Delete all prayer records and reset the store.
     */
    async deleteAllPrayers() {
      return DB.withTransaction(['prayer'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const clearReq = stores.prayer.clear();
          clearReq.onsuccess = () => {
            console.log('[PRAYER_DS] deleteAllPrayers SUCCESS');
            resolve(true);
          };
          clearReq.onerror = () => {
            console.error('[PRAYER_DS] deleteAllPrayers FAIL', clearReq.error);
            reject(clearReq.error);
          };
        });
      });
    }

    /**
     * Retrieve all prayer records.
     */
    async getAllPrayers() {
      return DB.withTransaction(['prayer'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.prayer.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              result.push(cursor.value);
              cursor.continue();
            } else {
              console.log('[PRAYER_DS] getAllPrayers SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] getAllPrayers FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Retrieve prayer times that are currently active.
     * A prayer is active if current time is between start and end times.
     */
    async getActivePrayers() {
      const now = Date.now();
      return DB.withTransaction(['prayer'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.prayer.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const prayer = cursor.value;
              if (prayer.start_time_in_milli_prayer <= now && 
                  prayer.end_time_in_milli_prayer > now) {
                result.push(prayer);
              }
              cursor.continue();
            } else {
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] getActivePrayers FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Check if current time falls within any prayer window.
     * Returns true if playback should be paused for prayer.
     */
    async isPrayerTimeActive() {
      const activePrayers = await this.getActivePrayers();
      const isActive = activePrayers.length > 0;
      return isActive;
    }

    /**
     * Get the next upcoming prayer time.
     * Returns the prayer record with the nearest future start time,
     * or null if no upcoming prayers.
     */
    async getNextPrayer() {
      const now = Date.now();
      return DB.withTransaction(['prayer'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          let nextPrayer = null;
          let minDiff = Infinity;
          const req = stores.prayer.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const prayer = cursor.value;
              const startTime = prayer.start_time_in_milli_prayer;
              if (startTime > now) {
                const diff = startTime - now;
                if (diff < minDiff) {
                  minDiff = diff;
                  nextPrayer = prayer;
                }
              }
              cursor.continue();
            } else {
              console.log('[PRAYER_DS] getNextPrayer SUCCESS prayer=' + (nextPrayer ? nextPrayer._id : 'none'));
              resolve(nextPrayer);
            }
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] getNextPrayer FAIL');
            resolve(null);
          };
        });
      });
    }

    /**
     * Get prayers for today based on date comparison.
     */
    async getTodaysPrayers() {
      const today = new Date();
      const todayStr = today.toISOString().slice(0, 10); // YYYY-MM-DD format
      
      return DB.withTransaction(['prayer'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.prayer.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const prayer = cursor.value;
              // Check if prayer date matches today
              if (prayer.start_prayer_date === todayStr || 
                  (prayer.start_prayer_date && prayer.start_prayer_date.includes(todayStr))) {
                result.push(prayer);
              }
              cursor.continue();
            } else {
              // Sort by start time
              result.sort((a, b) => (a.start_time_in_milli_prayer || 0) - (b.start_time_in_milli_prayer || 0));
              console.log('[PRAYER_DS] getTodaysPrayers SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[PRAYER_DS] getTodaysPrayers FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Check if a prayer with similar times already exists and update or create.
     * Uses start_time_in_milli_prayer as the key for comparison.
     *
     * @param {Object} prayer Prayer record to check/insert.
     * @returns {Promise<boolean>} True if updated, false if created.
     */
    async checkifPrayerExist(prayer) {
      return DB.withTransaction(['prayer'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.prayer.openCursor();
          let found = false;
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const existing = cursor.value;
              if (existing.start_time_in_milli_prayer === prayer.start_time_in_milli_prayer) {
                // Update existing
                const updated = Object.assign({}, existing, prayer, { _id: existing._id });
                cursor.update(updated);
                found = true;
                console.log('[PRAYER_DS] checkifPrayerExist UPDATE id=' + existing._id);
              }
              cursor.continue();
            } else {
              if (found) {
                resolve(true);
              } else {
                // Create new
                const addReq = stores.prayer.add(prayer);
                addReq.onsuccess = () => {
                  console.log('[PRAYER_DS] checkifPrayerExist CREATE');
                  resolve(false);
                };
                addReq.onerror = () => reject(addReq.error);
              }
            }
          };
          req.onerror = () => reject(req.error);
        });
      });
    }
  }

  // Expose globally
  window.PrayerDataSource = PrayerDataSource;
})();


