/**
 * SongsDataSource provides CRUD operations for the `songs` store.  This
 * is a partial port of the Android `SongsDataSource` class.  Only
 * methods required by the playlist manager and playback engine have
 * been implemented.  All methods return promises.
 */
(function () {
  class SongsDataSource {
    /**
     * Insert a new song record.  If the object does not contain an
     * `_id` property an auto‑incrementing key will be generated by
     * IndexedDB.
     *
     * @param {Object} song Song record with fields matching the
     *   `MySQLiteHelper.COLUMN_*` names, including sch_id,
     *   title_id, is_downloaded, titles, album_id, artist_id,
     *   time, artist_name, album_name, sp_playlist_id, song_path,
     *   song_url, serial_no, filesize, timeinterval, mediatype, reftime.
     */
    async createSongs(song) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.songs.add(song);
          req.onsuccess = () => {
            song._id = req.result;
            resolve(Object.assign({}, song));
          };
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Remove a song by its internal `_id`.  If `deleteSourceFile` is
     * true the file referenced by `song_path` will be removed via the
     * browser's file system API if available.  Since webOS does not
     * expose arbitrary filesystem access by default this operation
     * currently only removes the database entry.
     */
    async deleteSongs(song, deleteSourceFile = false) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.songs.delete(song._id);
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Delete all song records and reset the auto‑increment counter.
     */
    async deleteAll() {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const req = stores.songs.clear();
          req.onsuccess = () => resolve(true);
          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Retrieve all downloaded songs for a given playlist.  Songs are
     * returned in ascending order by their `serial_no`.  A song is
     * considered downloaded when `is_downloaded` equals 1.
     *
     * @param {string} playlistId The `sp_playlist_id` to filter on.
     */
    async getAllSongss(playlistId) {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const dedup = new Map();
          const index = stores.songs.index('splPlaylist_idx');
          const singleKeyRange = IDBKeyRange.only(playlistId);
          const req = index.openCursor(singleKeyRange);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 1) {
                const key = String(song.title_id || song._id || '');
                const prev = dedup.get(key);
                if (!prev || (!prev.song_path && song.song_path)) {
                  dedup.set(key, song);
                }
              }
              cursor.continue();
            } else {
              const result = Array.from(dedup.values());
              result.sort((a, b) => (a.serial_no || 0) - (b.serial_no || 0));
              resolve(result);
            }
          };
          req.onerror = () => {
            const result = Array.from(dedup.values());
            result.sort((a, b) => (a.serial_no || 0) - (b.serial_no || 0));
            resolve(result);
          };
        });
      });
    }

    /**
     * Retrieve downloaded songs for a playlist in random order.  This
     * method returns all songs where `is_downloaded == 1` regardless of
     * playlist ID.  If a playlist ID is provided it is ignored in the
     * random selection; use `getAllSongss` to constrain by playlist.
     */
    async getAllSongssRandom() {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.songs.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 1) {
                result.push(song);
              }
              cursor.continue();
            } else {
              // shuffle result
              for (let i = result.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [result[i], result[j]] = [result[j], result[i]];
              }
              resolve(result);
            }
          };
          req.onerror = () => resolve(result);
        });
      });
    }

    /**
     * Retrieve songs that are downloaded (is_downloaded == 1) for a
     * specific playlist.  This mirrors the Java method
     * `getSongsThoseAreDownloaded` but filters on `sp_playlist_id`.
     */
    async getSongsThoseAreDownloaded(playlistId) {
      return this.getAllSongss(playlistId);
    }

    /**
     * Retrieve songs that are not downloaded (is_downloaded == 0) for
     * a specific playlist.  Useful to determine which songs still
     * require downloading.
     */
    async getSongsThoseAreNotDownloaded(playlistId) {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const dedup = new Map();
          const index = stores.songs.index('splPlaylist_idx');
          const range = IDBKeyRange.only(playlistId);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 0) {
                const key = String(song.title_id || song._id || '');
                if (!dedup.has(key)) {
                  dedup.set(key, song);
                }
              }
              cursor.continue();
            } else {
              resolve(Array.from(dedup.values()));
            }
          };
          req.onerror = () => resolve(Array.from(dedup.values()));
        });
      });
    }

    /**
     * Update the download status and path for a song.  This method
     * expects a song object containing `title_id`, `is_downloaded` and
     * `song_path`.  All other fields are left unchanged.  Multiple
     * songs with the same title ID (across different playlists) will
     * be updated to reflect the new download status and path.
     */
    async updateSongsListWithDownloadstatusandPath(song) {
      const { title_id, is_downloaded, song_path } = song;
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const index = stores.songs.index('title_id_idx');
          const range = IDBKeyRange.only(title_id);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const existing = cursor.value;
              existing.is_downloaded = is_downloaded;
              existing.song_path = song_path;
              cursor.update(existing);
              cursor.continue();
            } else {
              resolve(true);
            }
          };
          req.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Delete all songs belonging to a specific playlist.
     * Mirrors Java `deleteSongsWithPlaylist`.
     *
     * @param {string} playlistId The sp_playlist_id to filter on.
     */
    async deleteSongsWithPlaylist(playlistId) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const index = stores.songs.index('splPlaylist_idx');
          const range = IDBKeyRange.only(playlistId);
          const req = index.openCursor(range);
          let deleteCount = 0;
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              cursor.delete();
              deleteCount++;
              cursor.continue();
            } else {
              console.log('[SONGS_DS] deleteSongsWithPlaylist SUCCESS playlist=' + playlistId + ' deleted=' + deleteCount);
              resolve(deleteCount);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] deleteSongsWithPlaylist FAIL playlist=' + playlistId);
            resolve(0);
          };
        });
      });
    }

    /**
     * Get all downloaded songs matching a specific title ID.
     * Mirrors Java `getAllDownloadedSongs(String Songid)`.
     *
     * @param {string} songId The title_id to filter on.
     */
    async getAllDownloadedSongs(songId) {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const index = stores.songs.index('title_id_idx');
          const range = IDBKeyRange.only(songId);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 1) {
                result.push(song);
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] getAllDownloadedSongs SUCCESS songId=' + songId + ' count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getAllDownloadedSongs FAIL songId=' + songId);
            resolve([]);
          };
        });
      });
    }

    /**
     * Get all songs that are downloaded for a playlist, verifying path exists.
     * Mirrors Java `getAllSongsThatAreDownloaded(String playlistID)`.
     * Since we can't check file existence in browser, we check if song_path is non-empty.
     *
     * @param {string} playlistId The sp_playlist_id to filter on.
     */
    async getAllSongsThatAreDownloaded(playlistId) {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const dedup = new Map();
          const index = stores.songs.index('splPlaylist_idx');
          const range = IDBKeyRange.only(playlistId);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 1 && song.song_path) {
                const key = String(song.title_id || song._id || '');
                const prev = dedup.get(key);
                if (!prev || (!prev.song_path && song.song_path)) {
                  dedup.set(key, song);
                }
              }
              cursor.continue();
            } else {
              const result = Array.from(dedup.values());
              console.log('[SONGS_DS] getAllSongsThatAreDownloaded SUCCESS playlist=' + playlistId + ' count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getAllSongsThatAreDownloaded FAIL playlist=' + playlistId);
            resolve(Array.from(dedup.values()));
          };
        });
      });
    }

    /**
     * Check if a song exists by title_id and playlist_id. If a song with
     * the same title_id exists in another playlist and is downloaded,
     * create a new entry with the downloaded status. Otherwise create new.
     * Mirrors Java `checkifSongExist`.
     *
     * @param {Object} song Song record to check/insert.
     */
    async checkifSongExist(song) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve, reject) => {
          const index = stores.songs.index('title_id_idx');
          const range = IDBKeyRange.only(song.title_id);
          const req = index.openCursor(range);

          let downloadedSong = null;
          let samePlaylistRecord = null;
          const duplicateIds = [];

          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const existing = cursor.value;
              const samePlaylist = String(existing.sp_playlist_id || '') === String(song.sp_playlist_id || '');

              if (samePlaylist) {
                if (!samePlaylistRecord) {
                  samePlaylistRecord = existing;
                } else {
                  const existingPriority = Number(existing.is_downloaded || 0) === 1 && !!existing.song_path;
                  const keepPriority = Number(samePlaylistRecord.is_downloaded || 0) === 1 && !!samePlaylistRecord.song_path;
                  if (existingPriority && !keepPriority) {
                    if (samePlaylistRecord._id != null) duplicateIds.push(samePlaylistRecord._id);
                    samePlaylistRecord = existing;
                  } else if (existing._id != null) {
                    duplicateIds.push(existing._id);
                  }
                }
              } else if (!downloadedSong && Number(existing.is_downloaded || 0) === 1 && existing.song_path) {
                downloadedSong = existing;
              }

              cursor.continue();
              return;
            }

            const finalizeDeletes = () => {
              duplicateIds.forEach((id) => {
                try {
                  stores.songs.delete(id);
                } catch (_e) {
                  // best effort
                }
              });
            };

            const applyDownloadCarryOver = (record) => {
              if (Number(record.is_downloaded || 0) === 1 && record.song_path) {
                return record;
              }
              if (downloadedSong) {
                record.is_downloaded = Number(downloadedSong.is_downloaded || 0);
                record.song_path = downloadedSong.song_path || record.song_path || '';
                record.filesize = downloadedSong.filesize || record.filesize || '';
                if (downloadedSong.timeinterval !== undefined && downloadedSong.timeinterval !== null) {
                  record.timeinterval = downloadedSong.timeinterval;
                }
              }
              return record;
            };

            if (samePlaylistRecord) {
              const updated = Object.assign({}, samePlaylistRecord, song, { _id: samePlaylistRecord._id });
              if (Number(samePlaylistRecord.is_downloaded || 0) === 1 && samePlaylistRecord.song_path) {
                updated.is_downloaded = Number(samePlaylistRecord.is_downloaded || 0);
                updated.song_path = samePlaylistRecord.song_path || '';
                updated.filesize = samePlaylistRecord.filesize || updated.filesize || '';
                if (samePlaylistRecord.timeinterval !== undefined && samePlaylistRecord.timeinterval !== null) {
                  updated.timeinterval = samePlaylistRecord.timeinterval;
                }
              }
              applyDownloadCarryOver(updated);

              const putReq = stores.songs.put(updated);
              putReq.onsuccess = () => {
                finalizeDeletes();
                console.log('[SONGS_DS] checkifSongExist SUCCESS(upsert) title=' + song.title_id);
                resolve(true);
              };
              putReq.onerror = () => reject(putReq.error);
              return;
            }

            const newSong = applyDownloadCarryOver(Object.assign({}, song));
            const addReq = stores.songs.add(newSong);
            addReq.onsuccess = () => {
              finalizeDeletes();
              console.log('[SONGS_DS] checkifSongExist SUCCESS(insert) title=' + song.title_id);
              resolve(false);
            };
            addReq.onerror = () => reject(addReq.error);
          };

          req.onerror = () => reject(req.error);
        });
      });
    }

    /**
     * Remove duplicate records inside a single playlist (same title_id).
     * Keeps the most useful record (downloaded+path preferred).
     */
    async removeDuplicateSongsForPlaylist(playlistId) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const keepByTitle = new Map();
          const deleteIds = [];
          const index = stores.songs.index('splPlaylist_idx');
          const range = IDBKeyRange.only(playlistId);
          const req = index.openCursor(range);

          const score = (song) => {
            var s = 0;
            if (Number(song.is_downloaded || 0) === 1) s += 2;
            if (song.song_path) s += 1;
            return s;
          };

          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              const key = String(song.title_id || song._id || '');
              if (!keepByTitle.has(key)) {
                keepByTitle.set(key, song);
              } else {
                const prev = keepByTitle.get(key);
                if (score(song) > score(prev)) {
                  if (prev._id != null) deleteIds.push(prev._id);
                  keepByTitle.set(key, song);
                } else if (song._id != null) {
                  deleteIds.push(song._id);
                }
              }
              cursor.continue();
            } else {
              deleteIds.forEach((id) => {
                try {
                  stores.songs.delete(id);
                } catch (_e) {
                  // best effort
                }
              });
              console.log('[SONGS_DS] removeDuplicateSongsForPlaylist SUCCESS playlist=' + playlistId + ' removed=' + deleteIds.length);
              resolve(deleteIds.length);
            }
          };

          req.onerror = () => {
            console.error('[SONGS_DS] removeDuplicateSongsForPlaylist FAIL playlist=' + playlistId);
            resolve(0);
          };
        });
      });
    }

    /**
     * Check if multiple songs with same title_id exist.
     * Mirrors Java `checkifSongsExist1`.
     *
     * @param {string} titleId The title_id to check.
     * @returns {Promise<boolean>} True if more than 1 song with this title exists.
     */
    async checkifSongsExist1(titleId) {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const index = stores.songs.index('title_id_idx');
          const range = IDBKeyRange.only(titleId);
          const countReq = index.count(range);
          countReq.onsuccess = () => {
            const exists = countReq.result > 1;
            console.log('[SONGS_DS] checkifSongsExist1 title=' + titleId + ' exists=' + exists);
            resolve(exists);
          };
          countReq.onerror = () => resolve(false);
        });
      });
    }

    /**
     * Update song with serial number and other fields.
     * Mirrors Java `updateSongsListWithSerialNumber`.
     *
     * @param {Object} song Song with serial_no, title_id, sp_playlist_id to update.
     */
    async updateSongsListWithSerialNumber(song) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const req = stores.songs.openCursor();
          let updated = false;
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const existing = cursor.value;
              if (existing.title_id === song.title_id &&
                  existing.sp_playlist_id === song.sp_playlist_id &&
                  existing.serial_no === song.serial_no) {
                existing.serial_no = song.serial_no;
                existing.artist_name = song.artist_name || existing.artist_name;
                existing.titles = song.titles || existing.titles;
                existing.is_downloaded = song.is_downloaded !== undefined ? song.is_downloaded : existing.is_downloaded;
                existing.song_path = song.song_path || existing.song_path;
                existing.timeinterval = song.timeinterval !== undefined ? song.timeinterval : existing.timeinterval;
                cursor.update(existing);
                updated = true;
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] updateSongsListWithSerialNumber SUCCESS updated=' + updated);
              resolve(updated);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] updateSongsListWithSerialNumber FAIL');
            resolve(false);
          };
        });
      });
    }

    /**
     * Get all unscheduled songs that are not downloaded.
     * Mirrors Java `getUnschdSongsThoseAreNotDownloaded`.
     */
    async getUnschdSongsThoseAreNotDownloaded() {
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.songs.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 0) {
                result.push(song);
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] getUnschdSongsThoseAreNotDownloaded SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getUnschdSongsThoseAreNotDownloaded FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Update download status to 0 for a song by its _id.
     * Mirrors Java `updateSongsColumnDownloadStatus`.
     *
     * @param {string|number} id The _id of the song record.
     */
    async updateSongsColumnDownloadStatus(id) {
      return DB.withTransaction(['songs'], 'readwrite', (stores) => {
        return new Promise((resolve) => {
          const getReq = stores.songs.get(Number(id));
          getReq.onsuccess = (event) => {
            const existing = event.target.result;
            if (existing) {
              existing.is_downloaded = 0;
              stores.songs.put(existing);
              console.log('[SONGS_DS] updateSongsColumnDownloadStatus SUCCESS id=' + id);
            }
            resolve(true);
          };
          getReq.onerror = () => {
            console.error('[SONGS_DS] updateSongsColumnDownloadStatus FAIL id=' + id);
            resolve(false);
          };
        });
      });
    }

    /**
     * Get songs for a playlist whose title_id is NOT in the provided array.
     * Used to find stale songs after syncing with server.
     * Mirrors Java `getSongListNotAvailableinWebResponse`.
     *
     * @param {string[]} titleIdArray Array of title IDs from server.
     * @param {string} playlistId The sp_playlist_id to filter on.
     */
    async getSongListNotAvailableinWebResponse(titleIdArray, playlistId) {
      if (!Array.isArray(titleIdArray)) titleIdArray = [];
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const index = stores.songs.index('splPlaylist_idx');
          const range = IDBKeyRange.only(playlistId);
          const req = index.openCursor(range);
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (!titleIdArray.includes(song.title_id)) {
                result.push(song);
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] getSongListNotAvailableinWebResponse SUCCESS playlist=' + playlistId + ' count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getSongListNotAvailableinWebResponse FAIL playlist=' + playlistId);
            resolve([]);
          };
        });
      });
    }

    /**
     * Get songs whose title_id is NOT in the provided array.
     * Used to find songs that need to be deleted.
     * Mirrors Java `getSongsToBeDeletedWithTitleIds`.
     *
     * @param {string[]} titleIds Array of title IDs to keep.
     */
    async getSongsToBeDeletedWithTitleIds(titleIds) {
      if (!Array.isArray(titleIds) || titleIds.length === 0) {
        return [];
      }
      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          const result = [];
          const req = stores.songs.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (!titleIds.includes(song.title_id)) {
                result.push(song);
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] getSongsToBeDeletedWithTitleIds SUCCESS count=' + result.length);
              resolve(result);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getSongsToBeDeletedWithTitleIds FAIL');
            resolve([]);
          };
        });
      });
    }

    /**
     * Get count of total songs downloaded that belong to active playlists.
     * Mirrors Java `getCountForTotalSongsDownloaded`.
     */
    async getCountForTotalSongsDownloaded() {
      // First get all distinct playlist IDs
      const playlistDS = new PlaylistDataSource();
      const playlists = await playlistDS.getAllDistinctPlaylists();
      const playlistIds = playlists.map(p => p.sp_playlist_id);

      return DB.withTransaction(['songs'], 'readonly', (stores) => {
        return new Promise((resolve) => {
          let count = 0;
          const req = stores.songs.openCursor();
          req.onsuccess = (event) => {
            const cursor = event.target.result;
            if (cursor) {
              const song = cursor.value;
              if (Number(song.is_downloaded) === 1 && playlistIds.includes(song.sp_playlist_id)) {
                count++;
              }
              cursor.continue();
            } else {
              console.log('[SONGS_DS] getCountForTotalSongsDownloaded SUCCESS count=' + count);
              resolve(count);
            }
          };
          req.onerror = () => {
            console.error('[SONGS_DS] getCountForTotalSongsDownloaded FAIL');
            resolve(0);
          };
        });
      });
    }
  }

  window.SongsDataSource = SongsDataSource;
})();